### ISSUE TITLE
Task: rename this repo to kebab-case

### ISSUE THREAD

**Issue by Kirill888** [WFP-VAM/hdc-algo#13]
I named this repo wrong, all the rest use `-` not `_`.

This will also involve updating S3 push role here:

https://github.com/WFP-VAM/seasmon-aws/blob/1c4323a01baefc230363dcc5ff7e5433d70bc862/cf-templates/svc_iam.yaml#L45

Unless we want a completely different name that is.

**Comment by valpesendorfer** [comment]
we will need a different name, as we do for `seasmon-aws`

**Comment by Kirill888** [comment]
Have we settled on `hdc-algo` for this repo?

**Comment by valpesendorfer** [comment]
closed with #36 🎉
